services:
  media_weightings:
    build: .
    container_name: lucos_media_weightings
    ports:
      - $PORT:$PORT
    environment:
      - PORT
      - MEDIA_API
      - MEDIA_METADATA_MANAGER_ORIGIN
      - TIME_API
      - KEY_LUCOS_MEDIA_METADATA_API
      - SCHEDULE_TRACKER_ENDPOINT
      - SYSTEM
      - LOGANNE_ENDPOINT
      - CLIENT_KEYS
    image: lucas42/lucos_media_weightings:${VERSION:-latest}
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
