version: 2.1
orbs:
  lucos: lucos/deploy@0
jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pipenv install
      - run:
          name: Run Tests
          command: ./test.py
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - lucos/build-amd64:
          context: docker
      - lucos/deploy-avalon:
          context: docker
          requires:
            - test
            - lucos/build-amd64
          filters:
            branches:
              only:
                - main